language: php
sudo: false
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

cache:
    directories:
        - $HOME/.composer/cache/files
        - ./bin/.phpunit

env:
    global:
        - PHPUNIT_FLAGS="-v"

matrix:
    fast_finish: true
    include:
        - php: 7.1
        - php: 7.2
        - php: 7.3
        - php: 7.4
        - php: 8.0

install:
    - composer install
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - ./vendor/bin/simple-phpunit install

script:
  - composer validate --strict --no-check-lock
  - ./vendor/bin/phpunit
