name: Symfony

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  symfony-tests:
    runs-on: ${{ matrix.operating-system }}
    name: PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }} on ${{ matrix.operating-system }}
    strategy:
      fail-fast: true
      matrix:
        operating-system: [ ubuntu-latest, windows-latest ]
        php: [ '7.2', '7.3', '7.4', '8.0', '8.1',  ]
        symfony: [ '5.4.*' ]

    steps:
      - uses: actions/checkout@master

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: flex

      - name: Download dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}
        uses: ramsey/composer-install@v1
        with:
          composer-options: "--no-progress --prefer-dist --optimize-autoloader"

      - name: Security check installed dependencies
        uses: symfonycorp/security-checker-action@v2

      - name: Run test suite on PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
        env:
          SYMFONY_DEPRECATIONS_HELPER: disabled
        run: ./vendor/bin/phpunit
